name: ppdyn
channels:
  - conda-forge
dependencies:
  - abseil-cpp=20210324.0=hbdafb3b_0
  - absl-py=0.12.0=pyhd8ed1ab_0
  - aiohttp=3.7.4=py38h30f7421_0
  - appnope=0.1.2=py38h10201cd_1
  - astor=0.8.1=pyh9f0ad1d_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py38h30f7421_1001
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.17.1=h27ca646_1
  - ca-certificates=2021.5.30=h4653dfc_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.2=pyhd8ed1ab_0
  - cairo=1.16.0=he69dfd1_1008
  - certifi=2021.5.30=py38h10201cd_0
  - cffi=1.14.5=py38he62ddd7_0
  - chardet=4.0.0=py38h10201cd_1
  - click=8.0.1=py38h10201cd_0
  - configparser=5.0.2=pyhd8ed1ab_0
  - cryptography=3.4.7=py38h3c0dae5_0
  - cycler=0.10.0=py_2
  - dataclasses=0.8=pyhc8e2a94_1
  - decorator=5.0.9=pyhd8ed1ab_0
  - ffmpeg=4.3.1=h22aafd7_2
  - fftw=3.3.9=nompi_h4173cc6_101
  - fontconfig=2.13.1=heb65262_1005
  - freetype=2.10.4=h17b34a0_1
  - gast=0.3.3=py_0
  - gettext=0.19.8.1=hea66d9f_1005
  - giflib=5.2.1=h27ca646_2
  - gmp=6.2.1=h9f76cd9_0
  - gnutls=3.6.13=h706517b_1
  - google-auth=1.30.0=pyh44b312d_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyh8c360ce_0
  - graphite2=1.3.13=h9f76cd9_1001
  - grpc-cpp=1.37.1=h69ac71c_0
  - grpcio=1.37.1=py38h69ee544_0
  - h5py=2.10.0=nompi_py38hb525b2d_106
  - harfbuzz=2.8.1=h86911b4_0
  - hdf5=1.10.6=nompi_h0fc092c_1114
  - icu=68.1=h17758a7_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=4.4.0=py38h10201cd_0
  - ipython=7.24.0=py38h2cb4d76_0
  - ipython_genutils=0.2.0=py_1
  - jasper=2.0.14=h9af5a26_2
  - jbig=2.1=h3422bc3_2003
  - jedi=0.18.0=py38h10201cd_2
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h27ca646_0
  - keras=2.4.3=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py38h12a6f45_1
  - krb5=1.19.1=hd92b7a7_0
  - lame=3.100=h27ca646_1001
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.12=had6a04f_0
  - lerc=2.2.1=h9f76cd9_0
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libcurl=7.77.0=h8fe1914_0
  - libcxx=11.1.0=h168391b_0
  - libdeflate=1.7=h27ca646_5
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.3=h9f76cd9_2
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_22
  - libgfortran5=11.0.1.dev0=hf114ba7_22
  - libglib=2.68.3=h6c200e4_0
  - libiconv=1.16=h642e427_0
  - liblapack=3.9.0=9_openblas
  - liblapacke=3.9.0=9_openblas
  - libllvm10=10.0.1=h4468dd5_2
  - libnghttp2=1.43.0=hf3018f0_0
  - libopenblas=0.3.15=openmp_hf330de4_1
  - libopencv=4.5.2=py38h3810feb_0
  - libpng=1.6.37=hf7e6567_2
  - libprotobuf=3.15.8=hccf11d3_0
  - libssh2=1.9.0=hb80f160_6
  - libtiff=4.3.0=hc6122e1_1
  - libwebp-base=1.2.0=h27ca646_2
  - libxml2=2.9.12=h538f51a_0
  - llvm-openmp=11.1.0=hf3c4609_1
  - llvmlite=0.36.0=py38h57246dd_0
  - lz4-c=1.9.3=h9f76cd9_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - matplotlib=3.4.2=py38h150bfb4_0
  - matplotlib-base=3.4.2=py38hb140015_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - multidict=5.1.0=py38h30f7421_1
  - ncurses=6.2=h9aa5885_4
  - nettle=3.6=hc6a1b29_0
  - numba=0.53.1=py38h5eaf91a_1
  - numpy=1.20.3=py38hbf7bb01_1
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.2=py38h150bfb4_0
  - openh264=2.1.1=habe5f53_0
  - openjpeg=2.4.0=h062765e_1
  - openssl=1.1.1k=h27ca646_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - ordered-set=4.0.2=py_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pcre=8.45=hbdafb3b_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.2.0=py38h5351710_1
  - pip=20.2.4=py_0
  - pixman=0.40.0=h27ca646_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - protobuf=3.15.8=py38h6f2b01f_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-opencv=4.5.2=py38hab544c7_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyevtk=1.2.0=pyh050c7b8_0
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pylatex=1.4.1=pyh9f0ad1d_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py38h10201cd_3
  - python=3.8.10=hf9733c0_1_cpython
  - python-dateutil=2.8.1=py_0
  - python-flatbuffers=1.12=pyhd8ed1ab_1
  - python_abi=3.8=1_cp38
  - pyyaml=5.4.1=py38h30f7421_0
  - re2=2021.04.01=hbdafb3b_0
  - readline=8.1=hedafd6a_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - scikit-learn=0.24.2=py38h26428f7_0
  - scipy=1.6.3=py38hd0c9ec0_0
  - setuptools=49.6.0=py38h10201cd_3
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=hc88da5d_3
  - sqlite=3.35.5=hc49ca36_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tensorflow-base=2.4.1=py38h42c5233_0
  - tensorflow-estimator=2.4.0=pyh9656e83_0
  - termcolor=1.1.0=py_2
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hf7e6567_1
  - tornado=6.1=py38h30f7421_1
  - tqdm=4.61.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - typeguard=2.12.0=pyhd8ed1ab_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.5=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3deb0d_0
  - wrapt=1.12.1=py38h30f7421_3
  - x264=1!161.3030=h3422bc3_1
  - xz=5.2.5=h642e427_1
  - yaml=0.2.5=h642e427_0
  - yarl=1.6.3=py38h30f7421_1
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h31e879b_1009
  - zstd=1.5.0=h861e0a7_0
  - pip:
    - ini-parser==1.2.0
    - pandas==1.2.4
    - pytz==2021.1
    - seaborn==0.11.1
    - sklearn==0.0
    - tensorflow==2.4.0rc0
    - tensorflow-addons==0.11.2
prefix: /Users/sayan/miniforge3/envs/apple_tensorflow
